# Generated by Django 4.0.4 on 2022-06-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_id', models.IntegerField(default=None)),
                ('Hospital_name', models.CharField(max_length=20)),
                ('Bed_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_id', models.IntegerField(default=None)),
                ('Doctor_name', models.CharField(max_length=20)),
                ('Join_date', models.DateTimeField()),
                ('Speciality', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('Experience', models.IntegerField(null=True)),
                ('Hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.hospital')),
            ],
        ),
    ]
